pegasus/apps/employees/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


app_name = "pegasus_employees"

urlpatterns = [
    path(
        "objects/",
        login_required(
            TemplateView.as_view(
                template_name="pegasus/employees/object_lifecycle_home.html",
                extra_context={"active_tab": "object_lifecycle"},
            )
        ),
        name="object_lifecycle_home",
    ),
    path("objects/django/", views.employee_list, name="django_object_lifecycle"),
    path("objects/django/new/", views.new_employee, name="django_new_employee"),
    path("objects/django/edit/<int:employee_id>/", views.edit_employee, name="django_edit_employee"),
    path("objects/django/delete/<int:employee_id>/", views.delete_employee, name="django_delete_employee"),
    path("objects/htmx/", views.employee_list_htmx, name="htmx_object_lifecycle"),
    path("objects/htmx/new/", views.new_employee_row_htmx, name="htmx_new_employee"),
    path("objects/htmx/empty/", views.empty_htmx, name="htmx_empty"),
    path("objects/htmx/edit/<int:employee_id>/", views.edit_employee_row_htmx, name="htmx_edit_employee"),
    path("objects/htmx/get/<int:employee_id>/", views.get_employee_row_htmx, name="htmx_get_employee"),
    path("objects/htmx/delete/<int:employee_id>/", views.delete_employee_htmx, name="htmx_delete_employee"),
    path("objects/react/", views.ReactObjectLifecycleView.as_view(), name="react_object_lifecycle"),
    path("objects/react/<path:path>", views.ReactObjectLifecycleView.as_view(), name="react_object_lifecycle_w_path"),
    path("objects/vue/", views.VueObjectLifecycleView.as_view(), name="vue_object_lifecycle"),
    path("charts/", views.ChartsView.as_view(), name="charts"),
    path("api/employee-data/", views.EmployeeDataAPIView.as_view(), name="employee_data"),
]


# drf config
router = routers.DefaultRouter()
router.register("api/employees", views.EmployeeViewSet)

urlpatterns += router.urls

pegasus/apps/examples/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = "pegasus_examples"

urlpatterns = [
    path("", views.ExamplesHomeView.as_view(), name="examples_home"),
    path(
        "pricing-page/",
        TemplateView.as_view(
            template_name="pegasus/examples/example_pricing_page.html", extra_context={"active_tab": "pricing_page"}
        ),
        name="pricing_page",
    ),
    # these are experimental examples that aren't currently exposed in the UI.
    path("alpine/", TemplateView.as_view(template_name="pegasus/examples/alpine_demo.html"), name="alpine_demo"),
    path("forms/", views.ExampleFormView.as_view(), name="form_demo"),
    path("forms/alpine/", views.AlpineFormView.as_view(), name="alpine_form_demo"),
    # tasks
    path("tasks/", views.TasksView.as_view(), name="tasks"),
    path("tasks/api/", views.tasks_api, name="tasks_api"),
    # flags
    path("flags/", views.FeatureFlagExampleView.as_view(), name="flags"),
]

skillplan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.api.v2.views import PagesAPIViewSet
from wagtail.contrib.sitemaps import Sitemap
from wagtail.documents import urls as wagtaildocs_urls
from apps.web.sitemaps import StaticViewSitemap

PagesAPIViewSet.schema = None  # hacky workaround for https://github.com/wagtail/wagtail/issues/8583

sitemaps = {
    "static": StaticViewSitemap(),
    "wagtail": Sitemap(),
}

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # redirect Django admin login to main login page
    path("admin/login/", RedirectView.as_view(pattern_name="account_login")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("apps.dashboard.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("subscriptions/", include("apps.subscriptions.urls")),
    path("ecommerce/", include("apps.ecommerce.urls")),
    path("", include("apps.web.urls")),
    path("pegasus/", include("pegasus.apps.examples.urls")),
    path("pegasus/employees/", include("pegasus.apps.employees.urls")),
    path("group-chat/", include("apps.group_chat.urls")),
    path("chat/", include("apps.chat.urls")),
    path("support/", include("apps.support.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # auth API
    path("api/auth/", include("apps.authentication.urls")),
    # API docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI - you may wish to remove one of these depending on your preference
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path("hijack/", include("hijack.urls", namespace="hijack")),
    # wagtail config
    # redirect Wagtail admin login to main login page
    path("cms/login/", RedirectView.as_view(pattern_name="account_login")),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("content/", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

pegasus/apps/employees/models.py
from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Employee(BaseModel):
    DEPARTMENT_CHOICES = (
        ("hr", "Human Resources"),
        ("finance", "Finance"),
        ("engineering", "Engineering"),
        ("marketing", "Marketing"),
        ("sales", "Sales"),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="employees")
    name = models.CharField(max_length=100, help_text="Your employee's name.")
    department = models.CharField(
        max_length=20, choices=DEPARTMENT_CHOICES, help_text="What department your employee belongs to."
    )
    salary = models.PositiveIntegerField(help_text="Your employee's annual salary.")

    def __str__(self):
        return self.name

pegasus/apps/employees/forms.py
from django import forms

from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("name", "department", "salary")

pegasus/apps/employees/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Sum, Count
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.templatetags.static import static
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST, require_http_methods
from django.views.generic import TemplateView
from drf_spectacular.utils import extend_schema_view, extend_schema
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.api.helpers import get_user_from_request
from apps.api.permissions import IsAuthenticatedOrHasUserAPIKey

from .forms import EmployeeForm
from .models import Employee
from .serializers import EmployeeSerializer, AggregateEmployeeDataSerializer


@login_required
def employee_list(request):
    return render(
        request,
        "pegasus/employees/list_employees.html",
        {"active_tab": "object_lifecycle", "employees": Employee.objects.filter(user=request.user)},
    )


@login_required
def new_employee(request):
    return _add_edit_employee(request)


@login_required
def edit_employee(request, employee_id):
    # don't forget to filter by user, else you'll allow people to edit other people's employees!
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee(request, employee)


def _add_edit_employee(request, employee: Employee = None):
    if employee:
        assert employee.user == request.user
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse("pegasus_employees:django_object_lifecycle"))
    else:
        form = EmployeeForm(instance=employee)

    return render(
        request,
        "pegasus/employees/edit_employee.html",
        {
            "active_tab": "object_lifecycle",
            "employee": employee,
            "form": form,
        },
    )


@require_POST
@login_required
def delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponseRedirect(reverse("pegasus_employees:django_object_lifecycle"))


@login_required
def employee_list_htmx(request):
    return render(
        request,
        "pegasus/employees/htmx_object_lifecycle.html",
        {"active_tab": "object_lifecycle", "employees": Employee.objects.filter(user=request.user)},
    )


@login_required
def new_employee_row_htmx(request):
    return _add_edit_employee_htmx(request)


@login_required
def edit_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee_htmx(request, employee)


def _add_edit_employee_htmx(request, employee=None):
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse("pegasus_employees:htmx_get_employee", args=[employee.id]))
    else:
        form = EmployeeForm(instance=employee)

    return render(
        request,
        "pegasus/employees/htmx/edit_employee_row.html",
        {
            "employee": employee,
            "form": form,
        },
    )


def empty_htmx(request):
    return HttpResponse("")


@login_required
def get_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return render(
        request,
        "pegasus/employees/htmx/employee_row.html",
        {
            "employee": employee,
        },
    )


@require_http_methods(["DELETE"])
@login_required
def delete_employee_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponse("")


@method_decorator(login_required, name="dispatch")
class ObjectLifecycleView(TemplateView):
    def get_context_data(self, **kwargs):
        return {
            "active_tab": "object_lifecycle",
            "department_choices": [{"id": c[0], "name": c[1]} for c in Employee.DEPARTMENT_CHOICES],
        }


class ReactObjectLifecycleView(ObjectLifecycleView):
    template_name = "pegasus/employees/react_object_lifecycle.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "framework_url": "https://reactjs.org/",
                "framework_name": "React",
                "framework_icon": static("images/pegasus/react-icon.png"),
                "url_base": reverse("pegasus_employees:react_object_lifecycle"),
            }
        )
        return context


class VueObjectLifecycleView(ObjectLifecycleView):
    template_name = "pegasus/employees/vue_object_lifecycle.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "framework_url": "https://vuejs.org/",
                "framework_name": "Vue.js",
                "framework_icon": static("images/pegasus/vue-icon.png"),
                "url_base": reverse("pegasus_employees:vue_object_lifecycle"),
            }
        )
        return context


@method_decorator(login_required, name="dispatch")
class ChartsView(TemplateView):
    template_name = "pegasus/employees/charts.html"

    def get_context_data(self, **kwargs):
        return {
            "active_tab": "charts",
        }


class EmployeeDataAPIView(APIView):
    permission_classes = (IsAuthenticatedOrHasUserAPIKey,)

    @extend_schema(operation_id="employees_aggregate_data", responses={200: AggregateEmployeeDataSerializer})
    def get(self, request):
        user = get_user_from_request(request)
        data = user.employees.values("department").annotate(
            average_salary=Avg("salary"),
            total_cost=Sum("salary"),
            number_employees=Count("pk"),
        )
        # data will look something like this:
        # [
        #     {'total_cost': 132000, 'number_employees': 2, 'average_salary': 66000.0, 'department': 'hr'},
        #     {'total_cost': 60000, 'number_employees': 1, 'average_salary': 60000.0, 'department': 'marketing'}
        # ]
        total_costs = [[row["department"], row["total_cost"]] for row in data]
        average_salaries = [[row["department"], row["average_salary"]] for row in data]
        headcounts = [[row["department"], row["number_employees"]] for row in data]
        return Response(
            {
                "total_costs": total_costs,
                "average_salaries": average_salaries,
                "headcounts": headcounts,
            }
        )


@extend_schema_view(
    create=extend_schema(operation_id="employees_create"),
    list=extend_schema(operation_id="employees_list"),
    retrieve=extend_schema(operation_id="employees_retrieve"),
    update=extend_schema(operation_id="employees_update"),
    partial_update=extend_schema(operation_id="employees_partial_update"),
    destroy=extend_schema(operation_id="employees_destroy"),
)
class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.employees.all()

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

pegasus/apps/examples/views/feature_flag_views.py
import waffle
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView


@method_decorator(login_required, name="dispatch")
class FeatureFlagExampleView(TemplateView):
    template_name = "pegasus/examples/example_feature_flag.html"

    def get_context_data(self, **kwargs):
        _create_flag_if_necessary()

        return {"active_tab": "flags", "flag_active": waffle.flag_is_active(self.request, "example-flag")}


def _create_flag_if_necessary():
    """Normally this would be done in a Django migration. Doing it here for convenience."""
    waffle.get_waffle_flag_model().objects.get_or_create(
        name="example-flag",
        defaults={
            "testing": True  # allows enabling via a URL param
        },
    )

pegasus/apps/examples/views/form_views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import FormView

from pegasus.apps.examples.forms import ExampleForm, ExampleFormAlpine


class ExampleFormView(FormView):
    template_name = "pegasus/examples/example_form.html"
    form_class = ExampleForm

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        messages.success(self.request, "Thanks for filling in the form!")
        return redirect("pegasus_examples:examples_home")


class AlpineFormView(FormView):
    template_name = "pegasus/examples/example_form_alpine.html"
    form_class = ExampleFormAlpine

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        messages.success(self.request, "Thanks for filling in the form!")
        return redirect("pegasus_examples:examples_home")

pegasus/apps/examples/views/tasks_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from ..tasks import progress_bar_task


@method_decorator(login_required, name="dispatch")
class TasksView(TemplateView):
    template_name = "pegasus/examples/tasks.html"

    def get_context_data(self, **kwargs):
        return {
            "active_tab": "tasks",
        }


@require_POST
def tasks_api(request):
    result = progress_bar_task.delay(5)
    return HttpResponse(result.task_id)

templates/pegasus/employees/charts.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
  <section class="app-card">
    <h1 class="pg-title">Charts Example</h1>
    <div id="page-overview" class="pg-content">
      <p>
        An end-to-end implementation of charts for your application, using <a href="https://www.chartjs.org/" target="_blank">Chart.js</a>,
        and based on data from the <a href="{% url 'pegasus_employees:object_lifecycle_home' %}">Employee App</a>.
      </p>
    </div>
    <div class="pg-columns">
      <div class="pg-column">
        <div class="pg-subtitle pg-text-centered">Budget by Department</div>
        <div id="department-spend-chart-wrapper">
          <canvas id="department-spend-chart"></canvas>
        </div>
      </div>
      <div class="pg-column">
        <div class="pg-subtitle pg-text-centered">Average Salary by Department</div>
        <div id="department-salaries-chart-wrapper">
          <canvas id="department-salaries-chart"></canvas>
        </div>
      </div>
    </div>
  </section>
  <div id="crud-home"></div>
{% endblock %}
{% block page_js %}
  <script src="{% static 'js/pegasus-bundle.js' %}" defer></script>
  <script>
    document.addEventListener('DOMContentLoaded', () => {

      const objectUrl = '{% url "pegasus_employees:react_object_lifecycle" %}';
      const Charts = SiteJS.pegasus.Charts;
      const client = SiteJS.pegasus.getPegasusApiClient("{{ server_url }}");

      client.employeesAggregateData().then(function (result) {
        if (result.headcounts.length === 0) {
          let noData = '<p class="pg-text-centered">No data! First <a href="' + objectUrl + '">create some employees</a>.</p>';
          document.getElementById('department-spend-chart-wrapper').innerHTML = noData;
          document.getElementById('department-salaries-chart-wrapper').innerHTML = noData;
        } else {
          Charts.renderChart('pie', 'department-spend-chart', result['totalCosts'], true);
          Charts.renderChart('bar', 'department-salaries-chart', result['averageSalaries'], false);
        }
      }).catch(error => {
        const errorDiv = document.createElement("div");
        errorDiv.innerHTML = "API loading failed. " +
          "If you are the site administrator and setting up your site for the first time, " +
          "see the documentation to resolve this: ";
        const docsLink = document.createElement("a");
        docsLink.setAttribute("href", "https://docs.saaspegasus.com/apis/#api-client-requests-are-failing");
        docsLink.innerText = "Troubleshooting API errors.";
        errorDiv.appendChild(docsLink);
        errorDiv.classList.add("pg-text-danger");
        document.getElementById('page-overview').appendChild(errorDiv);
      });
    });
  </script>
{% endblock %}

templates/pegasus/employees/django_object_lifecycle_base.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
  <nav aria-label="breadcrumbs">
    <ol class="pg-breadcrumbs">
      <li class=""><a href="{% url 'pegasus_employees:object_lifecycle_home' %}">Employee Lifecycle App</a></li>
      <li class="pg-breadcrumb-active" aria-current="page">Django Forms</li>
    </ol>
  </nav>
  <section class="app-card">
    <div class="pg-columns">
      <div class="pg-column-one-quarter pg-text-centered">
        <img class="img-fluid" alt="Django" src="{% static 'images/pegasus/django-icon.png' %}" style="max-height: 160px;"/>
      </div>
      <div class="pg-column">
        <h1 class="pg-title">Django Object Lifecycle Demo</h1>
        <h2 class="pg-subtitle">
          An interactive data model and UI example.
        </h2>
        <div class="pg-content">
          <p>
            This is an interactive data model and UI example using Django templates and forms.
            It demonstrates performing simple create, read, update and delete (CRUD) operations on an example
            "Employee" data model.
          </p>
        </div>
      </div>
    </div>
  </section>
  {% block django_app %}{% endblock %}
{% endblock %}

templates/pegasus/employees/edit_employee.html
{% extends "pegasus/employees/django_object_lifecycle_base.html" %}
{% load form_tags %}
{% block django_app %}
  <div class="app-card">
    <h2 class="pg-subtitle">Employee Details</h2>
    <form method="post">
      {% csrf_token %}
      {% render_form_fields form %}
      <input type="submit" value="Save Employee" class="pg-button-secondary">
    </form>
  </div>
{% endblock %}

templates/pegasus/employees/htmx_object_lifecycle.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block page_head %}
  <style>
    /* make an editable grid that looks like a table: https://stackoverflow.com/a/15600151/8207 */
    div.table
    {
        display:table;
    }
    form.tr, div.tr
    {
        display:table-row;
    }
    div.td, span.td, div.th, span.th
    {
        display:table-cell;
        width: inherit !important;
    }
    /* bootstrap styling workaround */
    .table > :not(:first-child) {
      border-top: none;
    }
  </style>
{% endblock page_head %}
{% block app %}
  <nav aria-label="breadcrumbs">
    <ol class="pg-breadcrumbs">
      <li class=""><a href="{% url 'pegasus_employees:object_lifecycle_home' %}">Employee Lifecycle App</a></li>
      <li class="pg-breadcrumb-active" aria-current="page">HTMX</li>
    </ol>
  </nav>
  <section class="app-card">
    <div class="pg-columns">
      <div class="pg-column-one-quarter pg-text-centered">
        <img class="img-fluid" alt="HTMX" src="{% static 'images/pegasus/htmx-icon.png' %}" style="max-height: 160px;"/>
      </div>
      <div class="pg-column">
        <h1 class="pg-title">HTMX Object Lifecycle Demo</h1>
        <h2 class="pg-subtitle">
          An interactive data model and UI example.
        </h2>
        <div class="pg-content">
          <p>
            This is an interactive data model and UI example built with <a href="https://htmx.org/" target="_blank">htmx</a>.
            This demo is built with native Django templates and forms and uses no native JavaScript!
          </p>
        </div>
      </div>
    </div>
  </section>
  <div class="app-card">
    <div class="table pg-table">
      <div class="tr">
        <div class="th pg-text-left">Name</div>
        <div class="th pg-text-left">Department</div>
        <div class="th pg-text-right">Salary</div>
        <div class="th"></div>
      </div>
      {% for employee in employees %}
        {% include 'pegasus/employees/htmx/employee_row.html' %}
      {% endfor %}
      {% include 'pegasus/employees/htmx/new_employee_button.html' %}
    </div>
  </div>
{% endblock %}
{% block page_js %}
<script>
  // hook up csrf tokens to all htmx requests
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>
{% endblock %}

templates/pegasus/employees/list_employees.html
{% extends "pegasus/employees/django_object_lifecycle_base.html" %}
{% load static %}
{% load i18n %}
{% block django_app %}
  <div class="app-card">
    {% if employees %}
      <div class="table-responsive">
        <table class="table pg-table">
          <thead>
          <tr>
            <th class="pg-text-left">{% translate "Name" %}</th>
            <th class="pg-text-left">{% translate "Department" %}</th>
            <th class="pg-text-right">{% translate "Salary" %}</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          {% for employee in employees %}
            <tr>
              <td>{{ employee.name }}</td>
              <td>{{ employee.get_department_display }}</td>
              <td class="pg-text-right">${{ employee.salary }}</td>
              <td class="pg-inline-buttons pg-justify-content-end">
                <a href="{% url 'pegasus_employees:django_edit_employee' employee.id %}">
                  <div class="pg-button-secondary">
                    <span class="pg-icon"><i class="fa fa-edit"></i></span>
                    <span class="pg-hidden-mobile-inline">{% translate "Edit" %}</span></div>
                </a>
                <form method="post" action="{% url 'pegasus_employees:django_delete_employee' employee.id %}">
                  {% csrf_token %}
                  <button class="pg-button-danger" type="submit" value="">
                    <span class="pg-icon"><i class="fa fa-times"></i></span>
                    <span class="pg-hidden-mobile-inline">{% translate "Delete" %}</span>
                  </button>
                </form>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <a class="pg-button-primary" href="{% url 'pegasus_employees:django_new_employee' %}">
        <span class="pg-icon"><i class="fa fa-plus"></i></span>
        <span>{% translate "Add Employee" %}</span>
      </a>
    {% else %}
      <div class="pg-columns">
        <div class="pg-column-one-third">
          <img class="img-fluid" alt="Nothing Here" src="{% static 'images/undraw/undraw_empty.svg' %}">
        </div>
        <div class="pg-column">
          <h1 class="pg-title">{% translate "No Employees Yet!" %}</h1>
          <h2 class="pg-subtitle">{% translate "Create your first employee below to get started." %}</h2>
          <div class="my-3">
            <a href="{% url 'pegasus_employees:django_new_employee' %}">
              <button class="pg-button-primary">
                <span class="pg-icon"><i class="fa fa-plus"></i></span><span>{% translate "Create Employee" %}</span>
              </button>
            </a>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/pegasus/employees/object_lifecycle.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
  <nav aria-label="breadcrumbs">
    <ol class="pg-breadcrumbs">
      <li class=""><a href="{% url 'pegasus_employees:object_lifecycle_home' %}">Employee Lifecycle App</a></li>
      <li class="pg-breadcrumb-active" aria-current="page">{{ framework_name }}</li>
    </ol>
  </nav>
  <section class="app-card">
    <div class="pg-columns">
      <div class="pg-column-one-quarter pg-text-centered">
        <img class="img-fluid" alt="{{ framework_name }}" src="{{ framework_icon }}" style="max-height: 160px;"/>
      </div>
      <div class="pg-column">
        <h1 class="pg-title">{{ framework_name }} Object Lifecycle Demo</h1>
        <h2 class="pg-subtitle">
          A single-page interactive data model and UI example.
        </h2>
        <div class="pg-content">
          <p>
            This is an interactive data model and UI example using
            <a href="https://www.django-rest-framework.org/" target="_blank">Django Rest Framework</a> and
            <a href="{{ framework_url }}" target="_blank">{{ framework_name }}</a>.
            It demonstrates performing simple create, read, update and delete (CRUD) operations on an example
            "Employee" data model.
          </p>
        </div>
      </div>
    </div>
  </section>
  <div id="object-lifecycle-home"></div>
{% endblock %}
{% block page_js %}
    {{ department_choices|json_script:'department-choices' }}
    <script>
        // initialize any page specific stuff here
        // static files that are used by the page javascript.
        const STATIC_FILES = {
            'undraw_empty': "{% static 'images/undraw/undraw_empty.svg' %}",
        };
        const EMPLOYEE_DEPARTMENT_CHOICES = JSON.parse(document.getElementById('department-choices').textContent);
        const urlBase = "{{ url_base }}";
        const SERVER_URL_BASE = "{{ server_url }}";
    </script>
    {% block framework_bundle %}
    {% endblock %}
{% endblock %}

templates/pegasus/employees/react_object_lifecycle.html
{% extends "pegasus/employees/object_lifecycle.html" %}
{% load static %}
{% block framework_bundle %}
  <script src="{% static 'js/react-object-lifecycle-bundle.js' %}" defer></script>
{% endblock %}

templates/pegasus/employees/vue_object_lifecycle.html
{% extends "pegasus/employees/object_lifecycle.html" %}
{% load static %}
{% block framework_bundle %}
  <script src="{% static 'js/vue-object-lifecycle-bundle.js' %}" defer></script>
{% endblock %}