apps/ecommerce/urls.py
from django.urls import path

from . import views

app_name = "ecommerce"

urlpatterns = [
    path("", views.ecommerce_home, name="ecommerce_home"),
    path("products/<slug:product_slug>/purchase/", views.purchase_product, name="purchase_product"),
    path("products/<slug:product_slug>/purchase/success/", views.checkout_success, name="checkout_success"),
    path("products/<slug:product_slug>/purchase/cancel/", views.checkout_cancelled, name="checkout_cancelled"),
    path("purchases/", views.purchases, name="purchases"),
    path("get/<slug:product_slug>/", views.access_product, name="access_product"),
]

skillplan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.api.v2.views import PagesAPIViewSet
from wagtail.contrib.sitemaps import Sitemap
from wagtail.documents import urls as wagtaildocs_urls
from apps.web.sitemaps import StaticViewSitemap

PagesAPIViewSet.schema = None  # hacky workaround for https://github.com/wagtail/wagtail/issues/8583

sitemaps = {
    "static": StaticViewSitemap(),
    "wagtail": Sitemap(),
}

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # redirect Django admin login to main login page
    path("admin/login/", RedirectView.as_view(pattern_name="account_login")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("apps.dashboard.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("subscriptions/", include("apps.subscriptions.urls")),
    path("ecommerce/", include("apps.ecommerce.urls")),
    path("", include("apps.web.urls")),
    path("pegasus/", include("pegasus.apps.examples.urls")),
    path("pegasus/employees/", include("pegasus.apps.employees.urls")),
    path("group-chat/", include("apps.group_chat.urls")),
    path("chat/", include("apps.chat.urls")),
    path("support/", include("apps.support.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # auth API
    path("api/auth/", include("apps.authentication.urls")),
    # API docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI - you may wish to remove one of these depending on your preference
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path("hijack/", include("hijack.urls", namespace="hijack")),
    # wagtail config
    # redirect Wagtail admin login to main login page
    path("cms/login/", RedirectView.as_view(pattern_name="account_login")),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("content/", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

apps/ecommerce/models.py
from functools import cached_property
from django.conf import settings
from django.templatetags.static import static
from django.db import models
from django.utils.translation import gettext_lazy as _
from djstripe.models import Price, Product

from apps.utils.billing import get_price_display_with_currency
from apps.utils.models import BaseModel


class ProductConfiguration(BaseModel):
    """
    Product Configuration for models that appear in your store.
    """

    slug = models.SlugField(max_length=128, unique=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    overview = models.TextField(
        blank=True, default="", help_text=_("Overview of the product, displayed on the store page.")
    )

    def __str__(self):
        return self.product.name

    @property
    def image_url(self):
        if self.product.images:
            return self.product.images[0]
        else:
            return static("images/undraw/undraw_happy_birthday.svg")

    @cached_property
    def price(self):
        return self.product.default_price

    @cached_property
    def readable_price(self):
        return get_price_display_with_currency(self.price.unit_amount_decimal / 100, self.price.currency)


class Purchase(BaseModel):
    """
    Purchases made by users
    """

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product_configuration = models.ForeignKey(ProductConfiguration, on_delete=models.CASCADE)
    # note: product is deprecated in favor of product_configuration and may be removed in an upcoming release
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.ForeignKey(Price, on_delete=models.CASCADE)
    checkout_session_id = models.CharField(max_length=100, unique=True, db_index=True)
    is_valid = models.BooleanField(default=True)

    def __str__(self):
        return f"Purchase of {self.product_configuration} by {self.user}"

apps/ecommerce/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import models
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import gettext as _
from apps.ecommerce.decorators import product_required

from apps.utils.billing import get_stripe_module
from apps.web.meta import absolute_url

from .helpers import create_purchase_from_checkout_session
from .models import ProductConfiguration, Purchase


@login_required
def ecommerce_home(request):
    products = (
        ProductConfiguration.objects.filter(is_active=True)
        .select_related("product", "product__default_price")
        .order_by("-created_at")
    ).annotate(
        owned=models.Subquery(
            models.Exists(
                Purchase.objects.filter(product_configuration=models.OuterRef("pk"), is_valid=True, user=request.user)
            )
        )
    )

    return TemplateResponse(
        request,
        "ecommerce/ecommerce_home.html",
        {
            "active_tab": "ecommerce",
            "products": products,
        },
    )


@login_required
def purchase_product(request, product_slug: str):
    product_config = get_object_or_404(
        ProductConfiguration.objects.select_related("product", "product__default_price"), slug=product_slug
    )
    stripe = get_stripe_module()
    success_url = absolute_url(reverse("ecommerce:checkout_success", args=[product_slug]))
    cancel_url = absolute_url(reverse("ecommerce:checkout_cancelled", args=[product_slug]))
    customer_kwargs = {}
    if request.user.customer:
        customer_kwargs["customer"] = request.user.customer.id
    else:
        customer_kwargs["customer_email"] = request.user.email
        # create a customer object so we can re-use it in future payments
        customer_kwargs["customer_creation"] = "always"

    checkout_session = stripe.checkout.Session.create(
        success_url=success_url + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url=cancel_url,
        payment_method_types=["card"],
        client_reference_id=request.user.id,
        mode="payment" if not product_config.product.default_price.recurring else "subscription",
        line_items=[
            {
                "price": product_config.product.default_price.id,
                "quantity": 1,
            },
        ],
        allow_promotion_codes=True,
        metadata={
            "source": "ecommerce",  # used by the webhook to only process checkouts from here
            "product_configuration_id": product_config.id,
        },
        **customer_kwargs,
    )
    return HttpResponseRedirect(checkout_session.url)


@login_required
def checkout_success(request, product_slug: str):
    # handle fulfillment
    product_config = get_object_or_404(ProductConfiguration.objects.select_related("product"), slug=product_slug)
    session_id = request.GET.get("session_id")
    session = get_stripe_module().checkout.Session.retrieve(session_id, expand=["line_items"])
    client_reference_id = int(session.client_reference_id)
    if client_reference_id != request.user.id:
        raise ValueError("User ID from checkout session did not match the logged-in user!")
    product_configuration_id = int(session.metadata.get("product_configuration_id"))
    if product_configuration_id != product_config.id:
        raise ValueError("Product configuration ID from checkout session did not match the product configuration!")
    create_purchase_from_checkout_session(session, product_config)
    messages.success(
        request,
        _("Your purchase of {product_name} was successful. Thanks for the support!").format(
            product_name=product_config.product.name
        ),
    )
    return HttpResponseRedirect(reverse("ecommerce:access_product", args=[product_slug]))


@login_required
def checkout_cancelled(request, product_slug: str):
    product_config = get_object_or_404(ProductConfiguration.objects.select_related("product"), slug=product_slug)
    messages.info(
        request, _("Your purchase of {product_name} was cancelled.").format(product_name=product_config.product.name)
    )
    return HttpResponseRedirect(reverse("ecommerce:ecommerce_home"))


@login_required
def purchases(request):
    purchases = Purchase.objects.filter(user=request.user)
    return TemplateResponse(
        request,
        "ecommerce/purchases.html",
        {
            "active_tab": "ecommerce",
            "purchases": purchases,
        },
    )


@login_required
@product_required
def access_product(request, product_slug: str):
    return TemplateResponse(
        request,
        "ecommerce/access_product.html",
        {
            "active_tab": "ecommerce",
            "product_config": request.product_config,  # set by the decorator
            "purchase": request.product_purchase,  # set by the decorator
        },
    )

templates/ecommerce/components/product_card.html
{% load static %}
{% load i18n %}
{% with product_config.product as product %}
<div class="pg-card h-100">
  <div class="pg-card-image">
    <figure class="image pg-ratio-3x2">
      <img class="img-fluid" src="{{ product_config.image_url }}" alt="{{ product.name }}">
    </figure>
  </div>
  <div class="pg-card-body mt-2" style="display: flex; flex-direction: column; justify-content: space-between;">
    <div>
      <h3 class="pg-title">{{ product.name }}</h3>
      <p class="pg-subtitle">
        {{ product_config.overview }}
      </p>
    </div>
    <div class="mt-2">
      {% if product.default_price %}
      <div class="mb-2">{{ product_config.price.human_readable_price }}</div>
      <div style="display: flex; align-items: baseline;">
        <a href="{% url 'ecommerce:purchase_product' product_config.slug %}" class="pg-button-secondary">
          <span>Buy</span>
        </a>
        {% if product_config.owned %}
        <a href="{% url 'ecommerce:access_product' product_config.slug %}" class="pg-button-primary" style="margin-left: .5rem;">
          <span>{% translate "Get" %}</span>
        </a>
        {% endif %}
      </div>
      {% else %}
      <div class="mb-2">
        {% translate "This product does not yet have a price and is so unavailable for purchase." %}
      </div>
      {% if product_config.owned %}
      <div>
        <a href="{% url 'ecommerce:access_product' product_config.slug %}" class="pg-button-primary">
          <span>{% translate "Get" %}</span>
        </a>
      </div>
      {% endif %}
      {% endif %}
    </div>
  </div>
</div>
{% endwith %}

templates/ecommerce/components/products_empty.html
{% load static %}
{% load i18n %}
<h2 class="pg-subtitle">{% translate "No Products Available!" %}</h2>
<p class="mt-2">
  If you are setting this project up for the first time, be sure to set up your products in Stripe,
  run <code>./manage.py bootstrap_ecommerce</code>,
  and set the <code>ACTIVE_ECOMMERCE_PRODUCT_IDS</code> in your settings/environment file.
  For more information, see the <a class="pg-link" href="https://docs.saaspegasus.com/payments">E-Commerce documentation</a>.
</p>

templates/ecommerce/components/purchases_empty.html
{% load static %}
{% load i18n %}
<div class="pg-columns">
  <div class="pg-column-one-third">
    <img class="img-fluid" alt="{% translate 'Nothing Here' %}" src="{% static 'images/undraw/undraw_empty.svg' %}">
  </div>
  <div class="pg-column">
    <h1 class="pg-title">{% translate "No Purchases" %}</h1>
    <h2 class="pg-subtitle">{% translate "When you buy a product from the store it will show up here." %}</h2>
    <p>
      <a class="pg-button-primary" href="{% url 'ecommerce:ecommerce_home' %}">
        <span>{% translate "View Store" %}</span>
      </a>
    </p>
  </div>
</div>