pegasus/apps/employees/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


app_name = "pegasus_employees"

urlpatterns = [
    path(
        "objects/",
        login_required(
            TemplateView.as_view(
                template_name="pegasus/employees/object_lifecycle_home.html",
                extra_context={"active_tab": "object_lifecycle"},
            )
        ),
        name="object_lifecycle_home",
    ),
    path("objects/django/", views.employee_list, name="django_object_lifecycle"),
    path("objects/django/new/", views.new_employee, name="django_new_employee"),
    path("objects/django/edit/<int:employee_id>/", views.edit_employee, name="django_edit_employee"),
    path("objects/django/delete/<int:employee_id>/", views.delete_employee, name="django_delete_employee"),
    path("objects/htmx/", views.employee_list_htmx, name="htmx_object_lifecycle"),
    path("objects/htmx/new/", views.new_employee_row_htmx, name="htmx_new_employee"),
    path("objects/htmx/empty/", views.empty_htmx, name="htmx_empty"),
    path("objects/htmx/edit/<int:employee_id>/", views.edit_employee_row_htmx, name="htmx_edit_employee"),
    path("objects/htmx/get/<int:employee_id>/", views.get_employee_row_htmx, name="htmx_get_employee"),
    path("objects/htmx/delete/<int:employee_id>/", views.delete_employee_htmx, name="htmx_delete_employee"),
    path("objects/react/", views.ReactObjectLifecycleView.as_view(), name="react_object_lifecycle"),
    path("objects/react/<path:path>", views.ReactObjectLifecycleView.as_view(), name="react_object_lifecycle_w_path"),
    path("objects/vue/", views.VueObjectLifecycleView.as_view(), name="vue_object_lifecycle"),
    path("charts/", views.ChartsView.as_view(), name="charts"),
    path("api/employee-data/", views.EmployeeDataAPIView.as_view(), name="employee_data"),
]


# drf config
router = routers.DefaultRouter()
router.register("api/employees", views.EmployeeViewSet)

urlpatterns += router.urls

pegasus/apps/examples/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = "pegasus_examples"

urlpatterns = [
    path("", views.ExamplesHomeView.as_view(), name="examples_home"),
    path(
        "pricing-page/",
        TemplateView.as_view(
            template_name="pegasus/examples/example_pricing_page.html", extra_context={"active_tab": "pricing_page"}
        ),
        name="pricing_page",
    ),
    # these are experimental examples that aren't currently exposed in the UI.
    path("alpine/", TemplateView.as_view(template_name="pegasus/examples/alpine_demo.html"), name="alpine_demo"),
    path("forms/", views.ExampleFormView.as_view(), name="form_demo"),
    path("forms/alpine/", views.AlpineFormView.as_view(), name="alpine_form_demo"),
    # tasks
    path("tasks/", views.TasksView.as_view(), name="tasks"),
    path("tasks/api/", views.tasks_api, name="tasks_api"),
    # flags
    path("flags/", views.FeatureFlagExampleView.as_view(), name="flags"),
]

skillplan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.api.v2.views import PagesAPIViewSet
from wagtail.contrib.sitemaps import Sitemap
from wagtail.documents import urls as wagtaildocs_urls
from apps.web.sitemaps import StaticViewSitemap

PagesAPIViewSet.schema = None  # hacky workaround for https://github.com/wagtail/wagtail/issues/8583

sitemaps = {
    "static": StaticViewSitemap(),
    "wagtail": Sitemap(),
}

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # redirect Django admin login to main login page
    path("admin/login/", RedirectView.as_view(pattern_name="account_login")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("apps.dashboard.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("subscriptions/", include("apps.subscriptions.urls")),
    path("ecommerce/", include("apps.ecommerce.urls")),
    path("", include("apps.web.urls")),
    path("pegasus/", include("pegasus.apps.examples.urls")),
    path("pegasus/employees/", include("pegasus.apps.employees.urls")),
    path("group-chat/", include("apps.group_chat.urls")),
    path("chat/", include("apps.chat.urls")),
    path("support/", include("apps.support.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # auth API
    path("api/auth/", include("apps.authentication.urls")),
    # API docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI - you may wish to remove one of these depending on your preference
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path("hijack/", include("hijack.urls", namespace="hijack")),
    # wagtail config
    # redirect Wagtail admin login to main login page
    path("cms/login/", RedirectView.as_view(pattern_name="account_login")),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("content/", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

pegasus/apps/employees/models.py
from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Employee(BaseModel):
    DEPARTMENT_CHOICES = (
        ("hr", "Human Resources"),
        ("finance", "Finance"),
        ("engineering", "Engineering"),
        ("marketing", "Marketing"),
        ("sales", "Sales"),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="employees")
    name = models.CharField(max_length=100, help_text="Your employee's name.")
    department = models.CharField(
        max_length=20, choices=DEPARTMENT_CHOICES, help_text="What department your employee belongs to."
    )
    salary = models.PositiveIntegerField(help_text="Your employee's annual salary.")

    def __str__(self):
        return self.name

pegasus/apps/employees/forms.py
from django import forms

from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("name", "department", "salary")

pegasus/apps/employees/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Sum, Count
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.templatetags.static import static
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST, require_http_methods
from django.views.generic import TemplateView
from drf_spectacular.utils import extend_schema_view, extend_schema
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.api.helpers import get_user_from_request
from apps.api.permissions import IsAuthenticatedOrHasUserAPIKey

from .forms import EmployeeForm
from .models import Employee
from .serializers import EmployeeSerializer, AggregateEmployeeDataSerializer


@login_required
def employee_list(request):
    return render(
        request,
        "pegasus/employees/list_employees.html",
        {"active_tab": "object_lifecycle", "employees": Employee.objects.filter(user=request.user)},
    )


@login_required
def new_employee(request):
    return _add_edit_employee(request)


@login_required
def edit_employee(request, employee_id):
    # don't forget to filter by user, else you'll allow people to edit other people's employees!
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee(request, employee)


def _add_edit_employee(request, employee: Employee = None):
    if employee:
        assert employee.user == request.user
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse("pegasus_employees:django_object_lifecycle"))
    else:
        form = EmployeeForm(instance=employee)

    return render(
        request,
        "pegasus/employees/edit_employee.html",
        {
            "active_tab": "object_lifecycle",
            "employee": employee,
            "form": form,
        },
    )


@require_POST
@login_required
def delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponseRedirect(reverse("pegasus_employees:django_object_lifecycle"))


@login_required
def employee_list_htmx(request):
    return render(
        request,
        "pegasus/employees/htmx_object_lifecycle.html",
        {"active_tab": "object_lifecycle", "employees": Employee.objects.filter(user=request.user)},
    )


@login_required
def new_employee_row_htmx(request):
    return _add_edit_employee_htmx(request)


@login_required
def edit_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee_htmx(request, employee)


def _add_edit_employee_htmx(request, employee=None):
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse("pegasus_employees:htmx_get_employee", args=[employee.id]))
    else:
        form = EmployeeForm(instance=employee)

    return render(
        request,
        "pegasus/employees/htmx/edit_employee_row.html",
        {
            "employee": employee,
            "form": form,
        },
    )


def empty_htmx(request):
    return HttpResponse("")


@login_required
def get_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return render(
        request,
        "pegasus/employees/htmx/employee_row.html",
        {
            "employee": employee,
        },
    )


@require_http_methods(["DELETE"])
@login_required
def delete_employee_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponse("")


@method_decorator(login_required, name="dispatch")
class ObjectLifecycleView(TemplateView):
    def get_context_data(self, **kwargs):
        return {
            "active_tab": "object_lifecycle",
            "department_choices": [{"id": c[0], "name": c[1]} for c in Employee.DEPARTMENT_CHOICES],
        }


class ReactObjectLifecycleView(ObjectLifecycleView):
    template_name = "pegasus/employees/react_object_lifecycle.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "framework_url": "https://reactjs.org/",
                "framework_name": "React",
                "framework_icon": static("images/pegasus/react-icon.png"),
                "url_base": reverse("pegasus_employees:react_object_lifecycle"),
            }
        )
        return context


class VueObjectLifecycleView(ObjectLifecycleView):
    template_name = "pegasus/employees/vue_object_lifecycle.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "framework_url": "https://vuejs.org/",
                "framework_name": "Vue.js",
                "framework_icon": static("images/pegasus/vue-icon.png"),
                "url_base": reverse("pegasus_employees:vue_object_lifecycle"),
            }
        )
        return context


@method_decorator(login_required, name="dispatch")
class ChartsView(TemplateView):
    template_name = "pegasus/employees/charts.html"

    def get_context_data(self, **kwargs):
        return {
            "active_tab": "charts",
        }


class EmployeeDataAPIView(APIView):
    permission_classes = (IsAuthenticatedOrHasUserAPIKey,)

    @extend_schema(operation_id="employees_aggregate_data", responses={200: AggregateEmployeeDataSerializer})
    def get(self, request):
        user = get_user_from_request(request)
        data = user.employees.values("department").annotate(
            average_salary=Avg("salary"),
            total_cost=Sum("salary"),
            number_employees=Count("pk"),
        )
        # data will look something like this:
        # [
        #     {'total_cost': 132000, 'number_employees': 2, 'average_salary': 66000.0, 'department': 'hr'},
        #     {'total_cost': 60000, 'number_employees': 1, 'average_salary': 60000.0, 'department': 'marketing'}
        # ]
        total_costs = [[row["department"], row["total_cost"]] for row in data]
        average_salaries = [[row["department"], row["average_salary"]] for row in data]
        headcounts = [[row["department"], row["number_employees"]] for row in data]
        return Response(
            {
                "total_costs": total_costs,
                "average_salaries": average_salaries,
                "headcounts": headcounts,
            }
        )


@extend_schema_view(
    create=extend_schema(operation_id="employees_create"),
    list=extend_schema(operation_id="employees_list"),
    retrieve=extend_schema(operation_id="employees_retrieve"),
    update=extend_schema(operation_id="employees_update"),
    partial_update=extend_schema(operation_id="employees_partial_update"),
    destroy=extend_schema(operation_id="employees_destroy"),
)
class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.employees.all()

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

pegasus/apps/examples/views/feature_flag_views.py
import waffle
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView


@method_decorator(login_required, name="dispatch")
class FeatureFlagExampleView(TemplateView):
    template_name = "pegasus/examples/example_feature_flag.html"

    def get_context_data(self, **kwargs):
        _create_flag_if_necessary()

        return {"active_tab": "flags", "flag_active": waffle.flag_is_active(self.request, "example-flag")}


def _create_flag_if_necessary():
    """Normally this would be done in a Django migration. Doing it here for convenience."""
    waffle.get_waffle_flag_model().objects.get_or_create(
        name="example-flag",
        defaults={
            "testing": True  # allows enabling via a URL param
        },
    )

pegasus/apps/examples/views/form_views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import FormView

from pegasus.apps.examples.forms import ExampleForm, ExampleFormAlpine


class ExampleFormView(FormView):
    template_name = "pegasus/examples/example_form.html"
    form_class = ExampleForm

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        messages.success(self.request, "Thanks for filling in the form!")
        return redirect("pegasus_examples:examples_home")


class AlpineFormView(FormView):
    template_name = "pegasus/examples/example_form_alpine.html"
    form_class = ExampleFormAlpine

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        messages.success(self.request, "Thanks for filling in the form!")
        return redirect("pegasus_examples:examples_home")

pegasus/apps/examples/views/tasks_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from ..tasks import progress_bar_task


@method_decorator(login_required, name="dispatch")
class TasksView(TemplateView):
    template_name = "pegasus/examples/tasks.html"

    def get_context_data(self, **kwargs):
        return {
            "active_tab": "tasks",
        }


@require_POST
def tasks_api(request):
    result = progress_bar_task.delay(5)
    return HttpResponse(result.task_id)

templates/pegasus/examples/alpine_demo.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
  <div class="app-card">
    <h1 class="pg-title">AlpineJS Demo</h1>
    <h2 x-data="{ message: 'I ❤️ Alpine' }" x-text="message" class="pg-subtitle"></h2>
    <div x-data="{ count: 0 }" class="mt-2">
      <button x-on:click="count++" class="pg-button-secondary">Increment</button>
      <span x-text="count"></span>
    </div>
    <div x-data="{ open: false }" class="mt-2">
      <button @click="open = ! open" class="pg-button-secondary">Toggle</button>
      <div x-show="open" @click.outside="open = false" class="mt-1">Contents...</div>
    </div>
    <div class="mt-2"
      x-data="{
          search: '',

          items: ['foo', 'bar', 'baz'],

          filteredItems() {
              return this.items.filter(
                  i => i.startsWith(this.search)
              )
          }
      }"
  >
      <input x-model="search" placeholder="Search..." class="pg-control">

      <ul class="mt-1">
          <template x-for="item in filteredItems()" :key="item">
              <li x-text="item"></li>
          </template>
      </ul>
    </div>
  </div>
{% endblock %}

templates/pegasus/examples/example_form.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% load form_tags %}
{% block app %}
<section class="app-card">
  <h2 class="pg-subtitle">Example Form</h2>
  <form method="post">
    {% csrf_token %}
    {% render_form_fields form %}
    <input type="submit" value="Save Data" class="pg-button-secondary">
  </form>
</section>
{% endblock %}

templates/pegasus/examples/example_form_alpine.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% load form_tags %}
{% block app %}
<section class="app-card">
  <h2 class="pg-subtitle">Example Form with Alpine.js customizations</h2>
  <form method="post" x-data="{ likeDjango: '{{ form.like_django.data|default:"yes" }}', styleValue: '{{ form.styled_options.data|default:"regular" }}' }">
    {% csrf_token %}
    {% render_field form.like_django %}
    {% render_field form.like_django_other xshow="likeDjango === 'other'" xcloak='True' %}
    {% render_field form.styled_options xbind__class="'pg-bg-' + styleValue" %}
    <p class="mt-4">You can also use alpine to display selected values.
      <em>
        Like Django: <strong x-text="likeDjango"></strong>,
        Style: <strong x-text="styleValue"></strong>
      </em>
    </p>
    <input type="submit" value="Save Data" class="pg-button-secondary mt-2">
  </form>
</section>
{% endblock %}

templates/pegasus/examples/example_pricing_page.html
{% extends "pegasus/examples/examples_base.html" %}
{% block app %}
  <section class="app-card">
    <h1 class="pg-subtitle">Need a pricing page?</h1>
    {% include 'pegasus/examples/components/tailwind_not_supported.html' %}
  </section>
{% endblock %}

templates/pegasus/examples/examples_base.html
{% extends "web/app/app_base.html" %}
{% block top_nav %}
  {% include 'pegasus/examples/components/top_nav_examples.html' %}
{% endblock %}
{% block sidebar-nav %}
  {% include "pegasus/examples/components/examples_nav.html" %}
{% endblock %}

templates/pegasus/examples/examples_home.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
<section class="app-card">
  <h1 class="pg-title">Examples Gallery</h1>
  <h2 class="pg-subtitle">
    End-to-end, fully functional examples for your project's needs.
  </h2>
</section>
  <div class="pg-columns">
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/object-demo-icons.png' %}" alt="Object Demo">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Employee Lifecycle</h3>
            <p>
              A front-end for working with your database implemented in vanilla Django, React, Vue.js, and HTMX.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_employees:object_lifecycle_home' %}" class="pg-button-secondary">
              <span>View Employee App</span>
              <span class="pg-icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/celery-icon.png' %}" alt="Background Tasks">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Background Tasks</h3>
            <p>
              Support background, long-running, or scheduled tasks easily with a working Celery
              + front-end integration.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:tasks' %}" class="pg-button-secondary">
              <span>View Tasks</span>
              <span class="pg-icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/undraw/undraw_analytics.svg' %}" alt="Charts">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Charts</h3>
            <p>
              Fully-integrated charts based on real data from your application.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_employees:charts' %}" class="pg-button-secondary">
              <span>View Charts</span>
              <span class="pg-icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="pg-columns mt-2">
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/flags.png' %}" alt="Feature Flags">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Feature Flags</h3>
            <p>
              Use Feature Flags to enable or disable portions of your site dynamically.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:flags' %}" class="pg-button-secondary">
              <span>View Feature Flag example</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/pricing-page-screenshot-small.png' %}" alt="Pricing Page">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="pg-content">
            <h3>Pricing Page</h3>
            <p>
              Communicate your application's value with a simple, flexible
              pricing page.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:pricing_page' %}" class="pg-button-secondary">
              <span>View Pricing Page</span>
              <span class="pg-icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

templates/pegasus/examples/tasks.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
<section class="app-card">
  <h3 class="pg-title">Tasks Example</h3>
  <p class="pg-subtitle">
    Support background, long-running, or scheduled tasks easily with Celery
  </p>
  <div class="pg-content">
    <p>
      Most applications eventually need to perform tasks that take longer than a few seconds to complete,
      for example data imports/exports.
      If yours is one of these, you'll probably want to use
      <a href="http://www.celeryproject.org/">Celery</a> for the job to run in the background.
    </p>
    <p>
      This page is a complete example that creates tasks for a background Celery process
      and displays the progress below.
      It should provide a perfect example to build from.
    </p>
    <p>
      <strong>Kick off your first Celery task below!</strong>
    </p>
    <button class="pg-button-primary mb-2" id="task-starter">
      <span>Run Task</span>
      <span class="pg-icon">
        <i class="fa fa-angle-double-right"></i>
      </span>
    </button>
    <div class="progress-bar-demo">
      <div class='progress-wrapper'>
        <div id="progress-bar" class='progress-bar'>&nbsp;</div>
      </div>
      <div id="progress-bar-message">Waiting for progress to start...</div>
    </div>
    <p>
      For more information about how this works see:
      <a href="https://www.saaspegasus.com/guides/django-celery-progress-bars/">
        Building Progress Bars for the Web with Django and Celery
      </a>
    </p>
  </div>
</section>
{% endblock %}
{% block page_js %}
    <script src="{% static 'celery_progress/celery_progress.js' %}" defer></script>
    <script src="{% static 'js/app-bundle.js' %}" defer></script>
    <script>
    const apiUrl = "{% url 'pegasus_examples:tasks_api' %}";
    const progressUrl = "{% url 'celery_progress:task_status' 'task-id-stub' %}";
    document.addEventListener("DOMContentLoaded", function () {
      const App = SiteJS.app;
      var trigger = document.getElementById('task-starter');
      trigger.addEventListener('click', function (e) {
          e.preventDefault();
          var pb = document.getElementById('progress-bar');
          pb.style.display = 'inherit';
          fetch(apiUrl, {
              method: 'post',
              credentials: 'same-origin',
              headers: {
                'X-CSRFToken': App.Cookies.get('csrftoken'),
              }
          }).then(
              function (response) {
                  return response.text();
              }).then(function (text) {
                  var taskUrl = progressUrl.replace('task-id-stub', text);
                  CeleryProgressBar.initProgressBar(taskUrl, {
                      onProgress: function (progressBarElement, progressBarMessageElement, progress) {
                          progressBarElement.style.width = progress.percent + "%";
                          progressBarMessageElement.innerHTML = progress.current + ' of ' + progress.total + ' processed.';
                      },
                  });
                })
                .catch(function (error) {
                  console.error('Request failed', error);
              });
              e.preventDefault();
      }, false);
    });
    </script>
{% endblock %}